app:
  myport: ${PORT:0}
server:
  port: ${app.myport}
spring:
  application:
    name: produto-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:produto
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/